// <auto-generated />
using System;
using HW1Week5.MyDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW1Week5.Migrations
{
    [DbContext(typeof(CodeAcademyBookingDB))]
    [Migration("20231218075633_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HW1Week5.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<int>("BookingDate")
                        .HasColumnType("int");

                    b.Property<int>("BookingTime")
                        .HasColumnType("int");

                    b.Property<string>("ReservationDeatails")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SpaceID")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username1")
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("BookingID");

                    b.HasIndex("SpaceID");

                    b.HasIndex("username1");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HW1Week5.Models.Space", b =>
                {
                    b.Property<int>("SpaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpaceID"));

                    b.Property<double>("AvaliableSpace")
                        .HasColumnType("float");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpaceID");

                    b.ToTable("spaces");
                });

            modelBuilder.Entity("HW1Week5.Models.User", b =>
                {
                    b.Property<string>("username")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("HW1Week5.Models.Booking", b =>
                {
                    b.HasOne("HW1Week5.Models.Space", null)
                        .WithMany("bookings")
                        .HasForeignKey("SpaceID");

                    b.HasOne("HW1Week5.Models.User", null)
                        .WithMany("bookings")
                        .HasForeignKey("username1");
                });

            modelBuilder.Entity("HW1Week5.Models.Space", b =>
                {
                    b.Navigation("bookings");
                });

            modelBuilder.Entity("HW1Week5.Models.User", b =>
                {
                    b.Navigation("bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
